### PR TITLE
Add landing page / milestone1

### PR DESCRIPTION
**Pull request by xsova113**
Add a landing page with a hero section and bit of animation for milestone 1.

### CODE REVIEW

**Comment by Divide-By-0** [comment]
1. Images seem to be broken: https://sendeth-staging.onrender.com/
2. Can you make it so only the airplane currently being hovered over moves, not all of them?
3. For the routing can you just set the existing app to show up at [sendeth.org/app](http://sendeth.org/app), and i'll also redirect [app.sendeth.org](http://app.sendeth.org/) to go to that url in the dns settings?
4. Can you make the existing website have more modular code and inherit consistent button styles etc?

It autodeploys, so feel free to add a commit here and it'll autoupdate in 5 minutes. Let me know if you want me to fix these commands:
Build Command: `npm install && npm run build && npx next export`
Publish directory (The relative path of the directory containing built assets to publish. Examples: ./, ./build, dist and frontend/build): `./out`

**Comment by xsova113** [comment]
I have fixed the annoying bug regarding deploying on render and next export problem. 2 things I added.
1. "npx serve@latest" in the "start" script in package.json 
2. output: "export", images: { unoptimized: true } in next.config file

the downside is with output: export, I cant use nextjs opotimized image and Image tag. I have to use regular img tag.

**Comment by Divide-By-0** [comment]
1. Got it. Can you give me an alternative set of commands I can put into render.com, so that we can render with the optimized images?

2. Can you make the color scheme of this logo complimentary or consistent, make the background transparent, and use it in place of the current bird? https://imgur.com/a/DKJd7te

3. With the chrome experimental flag to force dark mode, the circles get cut off (see below). It'll only be a useful fix for my own laptop. Alternatively we can have a native built-in dark mode for if the user's machine has set dark mode as the default! 
image

**Comment by xsova113** [comment]
1. This is the build command for render: "npm install && npm run build && npx next export".
Since we have to use output:export in next.config for nextjs to be deployed on render nextjs won't let me use optimized image. I am now using a package that optimized the image.

2. I will work on this logo.

3. OK, I will implement the dark mode feature.

**Comment by Divide-By-0** [comment]
Sweet, thanks for the shadow on the logo; it looks much better on light mode. Sometimes the transparency on the logo is gone, the contrast is messed up, and there seem to be two navbars on the demo site:
image

**Comment by Divide-By-0** [comment]
It still takes a second for the logo to change, and it has the colored background on dark mode for that second. Can you make the logo background transparent?

For blog, can you add one template post that's just a link to slides.sendeth.org, and another that compiles this .md as a .mdx or a .md, whatever's easier: https://github.com/Divide-By-0/blog/blob/main/content/posts/zkemail.md and another one that compiles this: https://github.com/Divide-By-0/blog/blob/main/content/posts/zk.md?

Also can you make the equations these:
- ([\w]+@[\w]+\.[\w]+)
- Az x Bz = Cz
- σ^e mod n = h(m)
- (a & b) ⊕ (a & c) ⊕ (b & c)

And finally can you make the planes, instead of just going in lines, go in loops between more floating circles, and "activate" the circles as they pass, by either color changing or having a short animation or bouncing or having a shadow or force animation come out, or what ever you think makes sense? This animation is complex so I can tip an extra $20 for it.
381044449_642842504704455_2194017784380165382_n

**Comment by xsova113** [comment]
> For blog, can you add one template post that's just a link to slides.sendeth.org, and another that compiles this .md as a .mdx or a .md, whatever's easier: https://github.com/Divide-By-0/blog/blob/main/content/posts/zkemail.md and another one that compiles this: https://github.com/Divide-By-0/blog/blob/main/content/posts/zk.md?

just to confirm, you'd like to have a post template as a link inside the blog page that link to slides.sendeth.org right? for 2 other that can open the md content and compiles to mdx?

**Comment by xsova113** [comment]
> And finally can you make the planes, instead of just going in lines, go in loops between more floating circles, and "activate" the circles as they pass, by either color changing or having a short animation or bouncing or having a shadow or force animation come out, or what ever you think makes sense? This animation is complex so I can tip an extra $20 for it.

I've never done an animation quite like this though, but I will try and see what I can do.

**Comment by Divide-By-0** [comment]
> > For blog, can you add one template post that's just a link to slides.sendeth.org, and another that compiles this .md as a .mdx or a .md, whatever's easier: https://github.com/Divide-By-0/blog/blob/main/content/posts/zkemail.md and another one that compiles this: https://github.com/Divide-By-0/blog/blob/main/content/posts/zk.md?
> 
> just to confirm, you'd like to have a post template as a link inside the blog page that link to slides.sendeth.org right? for 2 other that can open the md content and compiles to mdx?

That seems fine! And yeah looking forwards to the animation; if it doesn't work then happy to keep what we currently have!

**Comment by Divide-By-0** [comment]
Sweet. Blog post content still isn't loading. The email image you added in the new section on the home page under the original design overlaps with the text on mobile.

image

**Comment by Divide-By-0** [comment]
doesn't look properly centered in safari:
image

this equation also covers the text, which is not ideal placing. can we move it:
image

**Comment by Divide-By-0** [comment]
I like that one of the planes is covering the word "ZK". Can we make it fully cover "ZK" and only reveal it, when the plane movement animation happens? We can have that plane and 'ZK' enabled on mobile too.

**Comment by xsova113** [comment]
> Blog post content still isn't loading.

Thats weird. It's working in development mode. I'll work on this issue first then i'll work on the rest. Could be because we are using {outpost:export} and npx serve, not sure.

**Comment by xsova113** [comment]
I just made some test and i can confirm the output: "export" in next config is the problem. Removing that fixed the problem. Dynamic routing won't work with output:'export'. 

However, the problem now is if we remove output:export, the app can't be deployed on Render (not sure why). I will keep digging and see if theres any workaround.

**Comment by xsova113** [comment]
https://sendeth-1y18jpb6t-xsova113.vercel.app/.   I just tested deploying on Vercel. It worked perfectly fine without the output:export config. 
Dynamic routing and blog posts all work. But still failed to deploy on render (without output:export). 

Do you think it's possible to deploy with Vercel from now on or do you rather stick with Render? I find nextjs project with Render tend to get quite buggy.

**Comment by xsova113** [comment]
> doesn't look properly centered in safari:

my Safari doesnt seem to have this problem, but ill keep it in mind.

**Comment by Divide-By-0** [comment]
> https://sendeth-1y18jpb6t-xsova113.vercel.app/. I just tested deploying on Vercel. It worked perfectly fine without the output:export config. Dynamic routing and blog posts all work. But still failed to deploy on render (without output:export).
> 
> Do you think it's possible to deploy with Vercel from now on or do you rather stick with Render? I find nextjs project with Render tend to get quite buggy.

Vercel is ok. Prefer render of course, but if it'll take you longer than an hour to debug then vercel is fine

**Comment by Divide-By-0** [comment]
I'm on Vercel and all of these overlapping issues are still here. 
image

**Comment by Divide-By-0** [comment]
This one coming out the top also looks pretty bad:
image

**Comment by Divide-By-0** [comment]
pushed some changes so i can merge!

**Pull request merged**
